import React, { useMemo, useState } from 'react';
import { BriefcaseBusiness, IndianRupee, LogOut, UserPlus, UsersRound } from 'lucide-react';

const monthKey = () => new Date().toISOString().slice(0, 7);
const valueDate = (item) => String(item?.created_at || item?.joining_date || item?.resigned_date || item?.updated_at || '').slice(0, 10);
const money = (value) => Number(String(value || '0').replace(/[^\d.]/g, '')) || 0;
const formatINR = (value) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);

export default function FounderPersonalSpace({ projects = [], tasks = [], users = [] }) {
  const [mode, setMode] = useState('month');
  const [period, setPeriod] = useState(monthKey());
  const matches = (item) => valueDate(item).startsWith(period);
  const data = useMemo(() => {
    const periodProjects = projects.filter(matches);
    const periodTasks = tasks.filter(matches);
    const joined = users.filter((user) => String(user.joining_date || '').startsWith(period));
    const resigned = users.filter((user) => ['inactive', 'resigned'].includes(String(user.employment_status || '').toLowerCase()) && String(user.resigned_date || user.updated_at || '').startsWith(period));
    return { assigned: periodTasks.length, delivered: periodTasks.filter((task) => ['Completed', 'Done'].includes(task.status)).length, budget: periodProjects.reduce((total, project) => total + money(project.budget), 0), joined: joined.length, resigned: resigned.length, projects: periodProjects };
  }, [projects, tasks, users, period, mode]);
  return <div className="mx-auto max-w-6xl space-y-5"><section className="glass-card flex flex-col gap-4 p-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-xl font-bold">Personal space</h1><p className="mt-1 text-sm text-slate-500">A private founder view of delivery, budgets and workforce movement.</p></div><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-slate-900"><button onClick={() => { setMode('month'); setPeriod(monthKey()); }} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === 'month' ? 'bg-[var(--accent)] text-white' : 'text-slate-500'}`}>Month</button><button onClick={() => { setMode('year'); setPeriod(String(new Date().getFullYear())); }} className={`rounded-lg px-3 py-2 text-xs font-bold ${mode === 'year' ? 'bg-[var(--accent)] text-white' : 'text-slate-500'}`}>Year</button><input type={mode === 'month' ? 'month' : 'number'} min="2020" max="2100" value={period} onChange={(event) => setPeriod(event.target.value)} className="w-28 bg-transparent px-2 text-xs font-semibold outline-none" /></div></section><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card icon={BriefcaseBusiness} label="Tasks assigned" value={data.assigned} /><Card icon={BriefcaseBusiness} label="Tasks delivered" value={data.delivered} /><Card icon={IndianRupee} label="Project budget" value={formatINR(data.budget)} /><Card icon={UserPlus} label="Employees joined" value={data.joined} /><Card icon={LogOut} label="Employees resigned" value={data.resigned} /></section><section className="glass-card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="text-sm font-bold">Projects created in this period</h2><p className="mt-1 text-xs text-slate-500">Budget and delivery snapshot for the selected {mode}.</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{data.projects.map((project) => { const projectTasks = tasks.filter((task) => task.project_id === project.id); const complete = projectTasks.filter((task) => ['Completed', 'Done'].includes(task.status)).length; return <div key={project.id} className="flex items-center justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="truncate text-sm font-semibold">{project.title}</p><p className="mt-1 text-xs text-slate-500">{complete}/{projectTasks.length} tasks delivered · completion {project.deadline || 'Not set'}</p></div><p className="shrink-0 text-sm font-bold text-[var(--accent-ink)]">{formatINR(money(project.budget))}</p></div>; })}{!data.projects.length && <p className="px-5 py-10 text-center text-sm text-slate-500">No projects were created in this period.</p>}</div></section></div>;
}
function Card({ icon: Icon, label, value }) { return <div className="glass-card p-5"><Icon className="h-4 w-4 text-[var(--accent)]" /><p className="mt-3 text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
