import React, { useMemo, useState } from 'react';
import { Check, ListChecks, Plus, Trash2, UsersRound, X } from 'lucide-react';

const todayKey = () => new Date().toISOString().slice(0, 10);

export default function DailyTasksPage({ activeUser, users = [], dailyTasks = [], onCreate, onUpdate, onDelete }) {
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState({ title: '', dueDate: todayKey(), assigneeId: activeUser?.id || '' });
  const visibleTasks = useMemo(() => activeUser?.role === 'SUPER_ADMIN'
    ? dailyTasks
    : dailyTasks.filter((task) => task.assigned_to === activeUser?.id || task.assigned_to === 'ALL' || task.created_by === activeUser?.id), [dailyTasks, activeUser]);
  const submit = async (event) => {
    event.preventDefault();
    const person = users.find((user) => user.id === form.assigneeId);
    await onCreate({ title: form.title, dueDate: form.dueDate, assigneeId: form.assigneeId, assigneeName: form.assigneeId === 'ALL' ? 'All employees' : person?.name });
    setForm({ title: '', dueDate: todayKey(), assigneeId: activeUser?.id || '' });
    setShowCreate(false);
  };

  return <div className="mx-auto max-w-7xl space-y-5">
    <section className="glass-card flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ListChecks className="h-5 w-5 text-[var(--accent)]" /><h1 className="text-xl font-bold">Daily tasks</h1></div><p className="mt-1 text-sm text-slate-500">Standalone work outside projects. Each person completes company-wide tasks independently.</p></div><button onClick={() => setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4" />New daily task</button></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibleTasks.map((task) => <TaskCard key={task.id} task={task} activeUser={activeUser} onUpdate={onUpdate} onDelete={onDelete} />)}{!visibleTasks.length && <div className="glass-card col-span-full p-12 text-center"><ListChecks className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm text-slate-500">No daily tasks are assigned to you yet.</p></div>}</section>
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">New daily task</h2><p className="mt-1 text-xs text-slate-500">Assign a standalone task to one person or everyone.</p></div><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-5 w-5" /></button></div><label className="mt-5 block text-xs font-bold">Task name<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal outline-none focus:border-[var(--accent-line)] dark:border-slate-700 dark:bg-slate-800" /></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">Completion date<input required type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal outline-none focus:border-[var(--accent-line)] dark:border-slate-700 dark:bg-slate-800" /></label><label className="text-xs font-bold">Assign to<select value={form.assigneeId} onChange={(event) => setForm({ ...form, assigneeId: event.target.value })} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-normal outline-none focus:border-[var(--accent-line)] dark:border-slate-700 dark:bg-slate-800"><option value="ALL">All employees</option>{users.filter((user) => user.employment_status !== 'Inactive').map((user) => <option key={user.id} value={user.id}>{user.name || 'Unnamed teammate'}</option>)}</select></label></div><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-xl bg-slate-100 px-4 py-2.5 text-xs font-bold text-slate-700 dark:bg-slate-800 dark:text-slate-200">Cancel</button><button className="rounded-xl bg-[var(--accent)] px-4 py-2.5 text-xs font-bold text-white">Create task</button></div></form></div>}
  </div>;
}

function TaskCard({ task, activeUser, onUpdate, onDelete }) {
  const allEmployeesTask = task.assigned_to === 'ALL';
  const completions = task.completions || [];
  const completedByMe = allEmployeesTask ? completions.some((item) => item.user_id === activeUser?.id) : task.status === 'Completed';
  const overallStatus = allEmployeesTask ? `${completions.length} employee${completions.length === 1 ? '' : 's'} completed` : task.status;
  const isOverdueForMe = task.is_overdue && !completedByMe;
  return <article className={`glass-card p-5 ${isOverdueForMe ? 'border-rose-200 dark:border-rose-500/30' : ''}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-sm font-bold">{task.title}</p><p className="mt-1 text-xs text-slate-500">Assigned to {task.assigned_to_name}</p></div>{isOverdueForMe && <span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-bold text-rose-600 dark:bg-rose-500/10 dark:text-rose-300">Overdue</span>}</div><div className="mt-4 border-t border-slate-100 pt-3 text-xs dark:border-slate-800"><div className="flex items-center justify-between gap-3"><span className="text-slate-500">Due {task.due_date}</span><span className={`font-semibold ${completedByMe ? 'text-emerald-600' : 'text-slate-600 dark:text-slate-300'}`}>{allEmployeesTask ? (completedByMe ? 'Completed by you' : overallStatus) : overallStatus}</span></div>{allEmployeesTask && completions.length > 0 && <div className="mt-3 rounded-lg bg-slate-50 px-3 py-2 dark:bg-slate-900"><div className="flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wide text-slate-500"><UsersRound className="h-3.5 w-3.5" />Completed by</div><p className="mt-1.5 text-xs text-slate-700 dark:text-slate-300">{completions.map((item) => item.user_name || 'Employee').join(', ')}</p></div>}</div><div className="mt-3 flex justify-end gap-2">{!completedByMe && <button onClick={() => onUpdate(task.id, 'Completed')} className="inline-flex items-center gap-1 rounded-lg border border-emerald-200 px-2.5 py-1.5 text-xs font-bold text-emerald-700 hover:bg-emerald-50 dark:border-emerald-500/30 dark:text-emerald-300"><Check className="h-3.5 w-3.5" />Complete</button>}{activeUser?.role === 'SUPER_ADMIN' && <button onClick={() => { if (window.confirm(`Delete “${task.title}”?`)) onDelete(task.id); }} title="Delete daily task" className="rounded-lg p-1.5 text-slate-400 hover:bg-rose-50 hover:text-rose-600 dark:hover:bg-rose-500/10"><Trash2 className="h-4 w-4" /></button>}</div></article>;
}
